// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycfomqucllgatmpiefzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZm9tcXVjbGxnYXRtcGllZnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjYzNDUsImV4cCI6MjA4NjUwMjM0NX0.fd5Y5mL1_II2mUrb9TgddyAFpntzLvLEsLI5a45QXxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});